# Generated by Django 4.2.29 on 2026-03-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
