# Generated by Django 4.2.29 on 2026-03-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_options_product_breif_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='breif_description',
            new_name='brief_description',
        ),
    ]
