# Generated by Django 4.2.29 on 2026-03-28 18:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brief_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیح مختصر محصول'),
        ),
    ]
