# Generated by Django 4.2.29 on 2026-03-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_brief_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product'),
        ),
    ]
