# Generated by Django 4.2.29 on 2026-04-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productimagemodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimagemodel',
            old_name='Product',
            new_name='product',
        ),
    ]
