# Generated by Django 4.2.29 on 2026-04-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_wishlistproductmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
