# Generated by Django 4.2.29 on 2026-04-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_couponmodel_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='useraddressmodel',
            old_name='adress',
            new_name='address',
        ),
    ]
