# Generated by Django 4.2.29 on 2026-04-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['-created_date']},
        ),
    ]
